### ISSUE TITLE
math_counter problem

### ISSUE THREAD

**Issue by Slow69me** [samuelmaddock/zombie-escape#5]
```
[ERROR] gamemodes/zombieescape/gamemode/modules/boss/ents/entities/math_counter/init.lua:107: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. unknown - gamemodes/zombieescape/gamemode/modules/boss/ents/entities/math_counter/init.lua:107
    3. Input - [C]:-1
     4. unknown - gamemodes/base/entities/entities/base_entity/outputs.lua:53
```

any idea? map: ze_skyrimfixv4, ze_bioshock and much more.

**Comment by samuelmaddock** [comment]
Here's the section of code causing the problem. https://github.com/samuelmaddock/zombie-escape/blob/master/ZombieEscape/gamemode/modules/boss/ents/entities/math_counter/init.lua#L104-L109

An entity in that map is firing the `GetValue` input to the math_counter entity, but there are no `OnGetValue` outputs registered. Try changing that section of code to the following and let me know if it's fixed.

```lua
elseif name == "getvalue" then
		-- Update outvalue before firing
		if istable(self.Outputs.OnGetValue) then
			for k, v in pairs(self.Outputs.OnGetValue) do
				v.param = self.m_OutValue
			end
		end

		self:TriggerOutput("OnGetValue", activator)
```

**Comment by Slow69me** [comment]
I've changed to this code and its fixed for some the maps.

Another error in ze_bioshock_v5_6.

`[ERROR] gamemodes/zombiesurvival/entities/entities/math_counter/init.lua:154: attempt to compare number with nil
  1. UpdateOutValue - gamemodes/zombiesurvival/entities/entities/math_counter/init.lua:154
   2. unknown - gamemodes/zombiesurvival/entities/entities/math_counter/init.lua:77
    3. Input - [C]:-1
     4. unknown - gamemodes/base/entities/entities/base_entity/outputs.lua:53
`

**Comment by samuelmaddock** [comment]
@Slow69me [add me on Steam](http://steamcommunity.com/id/__samm/) and let me know who you are in the comments.

**Comment by Slow69me** [comment]
@samuelmaddock I added yet.

**Comment by samuelmaddock** [comment]
Fixed. I ended up recoding the math_counter entity to closer match the C++ code in the Source Engine. I also discovered that Garry's Mod's scripted entity trigger event firing system doesn't respect the original Source Engine implementation's behavior. That uses an event queue while GMod fires events immediately.
