### ISSUE TITLE
Zombie bosses take no damage from bullets

### ISSUE THREAD

**Issue by ottomanaf** [samuelmaddock/zombie-escape#6]
On maps with bossfights (that exist in 'gamemode/maps/mapname.lua') the bosses receive no damage from any attack save for melee (knife,crowbar) attacks.
Health bar only ever changes from either boss damaging itself (predator's AOE shots can hurt himself naturally) or being meleed by players.Bullets basically go through the bosses.

Specifically on ze_TESV_Skyrim_v3 the error prints:

> ERROR: Tried to SetParentAttachment for entity func_breakable (finalboss_tar), but it has no attachment named primary.

Example maps are below:

```
ze_predator_ultimate_v3   (predator)
ze_TESV_Skyrim_v3   (anduin)
ze_bioshock_v5_6   (big daddy)

```

In addition to this, on the map ze_minecraft_v1_1 , the buttons that open wooden doors don't work at all, not responding to +use bound button.

The server that was used to test this is still up and I'd be happy to provide access should you need it.

**Comment by samuelmaddock** [comment]
The `SetParentAttachment` errors are related to entity IO relying on CS:S player model attachments. If you force all player's to use a CS:S player model, it will likely work.

I have a fix in a fork of Zombie Survival https://github.com/samuelmaddock/zombiesurvival/commit/74aaeb2c2ffc8d5a848945162618de00aacbec72

**Comment by ottomanaf** [comment]
The fix above has solved the issue, thanks!
And the button issue is specific to that map, so I can just avoid the map
